### ISSUE TITLE
parse_dsv_emails() missing

### ISSUE THREAD

**Issue by pkurosinski** [michael-milette/moodle-enrol_invitation#1]
Hi Michael,

I installed your Initial 0.1 pre-ALPHA release (thanks for sharing!) on Moodle 3.9.6
When inviting a user, there is an exception:
Exception - Call to undefined method invitation_form::parse_dsv_emails()
line 113 of /enrol/invitation/invitation.php: Error thrown

Best regards,
Pascal

**Comment by bfriesenvcc** [comment]
I get the same.

<img width="284" alt="InviteUserErrors" src="https://user-images.githubusercontent.com/8193384/146281403-7f48d59e-d9a6-4e35-8a47-8be1134d35e0.PNG">

**Comment by michael-milette** [comment]
Hi @pkurosinski  and @bfriesenvcc ,

Thank you for reporting the issue. It is now fixed here on GitHub. Please give it a try when you have a chance and let me know if it works for you.

Best regards,

Michael

**Comment by bfriesenvcc** [comment]
That seems to have done the trick! 
I haven't been able to fully test because our test server has email turned off (Not sending email due to $CFG->noemailever config setting), but we've definitely made progress! 
Thanks, Michael!

**Comment by michael-milette** [comment]
Hi @bfriesenvcc ,

Glad to hear it resolved the issue for you. Thank you for letting me knwo.

Please feel free to open a new issue if you come across any additional issues. I really appreciate feedback.

Best regards,

Michael
