### ISSUE TITLE
Make date format strings localizable

### ISSUE THREAD

**Issue by pete1854** [michael-milette/moodle-enrol_invitation#24]
Hi,

Thanks for a great plugin!

Currently the dates shown in the history page seems not to be possible to format according to the local culture.

The code can be found in ```history.php``` on line 175.
```PHP
// When was the invite sent?
$row[3] = date('Y-m-j g:ia', $invite->timesent);
// When does the invite expire?
$row[4] = date('Y-m-j g:ia', $invite->timeexpiration);
```

I would like to suggest that the date format strings are put in the language file to make them possible to localize.
Kind regards,
Peter

**Comment by michael-milette** [comment]
Hi @pete1854 ,

Thank you for testing this plugin and reporting the issue. It is now fixed here on GitHub. It now uses the localized strftimedatetimeshort date format. I would appreciate it if you would be so kind as to test it out and let me know if the fix works for you.

Best regards,

Michael

**Comment by pete1854** [comment]
Hi!
Thanks for your quick response to this issue! I've tested it and the date is now formatted correctly.
Kind regards,
Peter

**Comment by michael-milette** [comment]
Thanks for letting me know Peter. Your help is much appreciated! :-)

Michael
