### ISSUE TITLE
Add blank space to string

### ISSUE THREAD

**Issue by pete1854** [michael-milette/moodle-enrol_invitation#25]
Hi,

I found another thing in the history page:

The "Accepted by..." string is written as "Acceptedby..." (no space between 'Accepted' and 'by...')

I believe I have found the bug. If you look att line 165 in ```history.php``` there seems to be a missing ```' '```

```$row[2] .= get_string('used_by', 'enrol_invitation', $result);```
should be 
```$row[2] .= ' ' . get_string('used_by', 'enrol_invitation', $result);```

Kind regards,
Peter

**Comment by michael-milette** [comment]
Hi @pete1854 ,

Thank you for testing this plugin and reporting the issue. It is now fixed here on GitHub. It now uses the localized strftimedatetimeshort date format. I would appreciate it if you would be so kind as to test it out and let me know if the fix works for you.

Best regards,

Michael

**Comment by pete1854** [comment]
Hi again, @michael-milette 

This also works :)
Kind reagrds,
Peter

**Comment by michael-milette** [comment]
Thanks for your feedback Peter!
