### ISSUE TITLE
Blank 'userfullname' and 'useremail' in enrol confirmation e-mail message

### ISSUE THREAD

**Issue by pete1854** [michael-milette/moodle-enrol_invitation#27]
Hi @michael-milette,

I might have found another issue. The e-mail notification sent to the inviter contains null/blank values for the

```$a->userfullname``` and ```$a->useremail``` properties

in ```{$a->userfullname} ({$a->useremail}) has accepted your invitation to access...``` (string id: emailmessageuserenrolled)

resulting in the message looking like this:

>Hello
>
>() has accepted your invitation to access S281: Lifecare HSL e-Utbildning as a "Kursdeltagare". You can verify the  status of this invitation by viewing either:
>
>* Participant list: removed for brevity
>* Invitation history: removed for brevity
>
> remaining text removed for brevity

https://github.com/michael-milette/moodle-enrol_invitation/blob/4e541d061a3f7022fff313beb28173f19d5a3ee5/enrol.php#L270-L271

Kind regards,
Peter

**Comment by michael-milette** [comment]
Hi @pete1854 

Thanks again for reporting the bug. The issue has been resolved. If you have a chance, please take a moment to try out the latest version here on GitHub and let me know how it goes.

Best regards,

Michael

**Comment by michael-milette** [comment]
As there has been no further discussion on this topic and the issue has been resolved, I will close this issue.
