### ISSUE TITLE
prepare_notice_object() function missing

### ISSUE THREAD

**Issue by pkurosinski** [michael-milette/moodle-enrol_invitation#3]
Hi Michael,
Thanks for the fix from December. It works well. However, I think there is another function missing. If a non-logged user licks the "Accept" link, the error is: Exception - Call to undefined function prepare_notice_object()
Looks like there was supposed to be a warning instead? 
Best regards,
Pascal

**Comment by michael-milette** [comment]
Thanks @pkurosinski , I appreciate your feedback. I am in the process of preparing it for a release on Moodle.org but will take a look at this issue shortly.

**Comment by michael-milette** [comment]
Hi @pkurosinski ,

The issue was that the function was only renamed in some places. I pushed a fix here on GitHub but did not test it yet. If you have a chance, feel free to test it and let me know how it goes. 

Otherwise, I will some time within the next week or so.

Best regards,

Michael

**Comment by pkurosinski** [comment]
Hi Michael,

I tested the beta version you released today. The bug is gone. Thanks!

Best regards,
Pascal

**Comment by michael-milette** [comment]
Hi @pkurosinski ,

Through much testing today, I discovered a bunch of issues with accepting and rejecting invitations. I hope you will find the latest 1.3.1 release (2022-01-13) much more stable and reliable. Thank you for taking the time to test. I really appreciate it.

Best regards,

Michael
