### ISSUE TITLE
Send invitation for unregistered users

### ISSUE THREAD

**Issue by atrolex** [michael-milette/moodle-enrol_invitation#31]
Please explain how this option is working:
![image](https://user-images.githubusercontent.com/33658481/173321339-940f63b1-4795-4d87-8d8a-927c33b18a9b.png)

The option is set to "No" and I send the invitation to someone not registered in the system. An unregistered user clicks on the button "Accept invitation" he sees login form:
![image](https://user-images.githubusercontent.com/33658481/173322464-21abd038-2e13-4bdf-afd4-182f291435e6.png)

What is "accept invitation" exactly in the case of the unregistered user?

Moreover by sending invites I am able to choose the cohort.
![image](https://user-images.githubusercontent.com/33658481/173322110-c56c73d7-17a7-460f-a6a1-c753cdc8b0bc.png)

If an invited user is not registered user, how he can be added to cohort?

**Invitation for registration:**
I think it would be helpful if the unregistered user by clicking on the "Accept invitation" button would be redirected to a self-registration form (don't not matter if it is activated in global configuration or not), where he can create an account for him. Which than should be linked to the cohort and the course.

**Comment by michael-milette** [comment]
"Send invitation only for registered users" will prevent sending invitations to email addresses if the user does not already have an account.

**Comment by michael-milette** [comment]
"Accept invitation" for a user who does not already have an account does nothing until the user creates an account. Once they do, or if they already havd, they will automatically be enrolled in the course when they log in.

**Comment by michael-milette** [comment]
"Cohorts": You need to add a user to a cohort manually or in some other way. Invitation just enrolls them in the course. Cohorts are tied to a user's account, not their enrolment in a course.

This is more useful if you are dealing with people who already have an account in your Moodle sife.

**Comment by michael-milette** [comment]
"Invitation for registration": I noticed that you don't have Email-based Self-Registration enabled. Once you enable this Moodle feature, a new link will appear on the Login page enabling users to create a new account for themselves.

For more information on this, see:
https://docs.moodle.org/en/Email-based_self-registration

**Comment by michael-milette** [comment]
Regarding automatically assigning users to cohorts upon account creation, take a look at the Auto-Cohort plugin:
 https://moodle.org/plugins/local_cohortauto

As this topic is behond the scope of the Invitation plugin, if you have any further questions about it, you are welcome to hire me to work with you or to submit your questions in the Moodle discussion forums.

To hire me, I can be reached through my website at https://www.tngconsulting.ca/contact

Best regards,

Michael

**Comment by atrolex** [comment]
Hello @michael-milette  for your detailed comments. It was very helpful!
