### ISSUE TITLE
Feature Request: 

### ISSUE THREAD

**Issue by hribeir0** [michael-milette/moodle-enrol_invitation#34]
### Prerequisites

- [X] I am requesting the new feature to the correct repository.
- [X] I checked the latest version on GitHub and the [README.md](../blob/master/README.md) documentation to ensure that this functionality does not already exist.
- [X] I searched to make sure that this feature has not already been requested.
- [X] I have, or I know someone who has, the ability and willingness to test the new feature on a Moodle LMS-based site.
- [X] I agree to submit one feature request per issue ticket (do not submit multiple requests in one issue ticket).
- [X] I understand that development and support is provided by volunteer(s) and that all final implementation decisions are up TNG Consulting Inc.

### Feature Request - The User Story

As a Moodle Manager I want to add multi instances of the enrol_invitation plugin to invite users for different roles.
So, one group of users will be awarded the student role, other group of users will be awarded the tutor role after accepting the invitation

### Planning on submitting a solution in a pull request (PR)?

Maybe

### Code of Conduct

- [X] I have read and agree to the project's <a href="../blob/master/CODE_OF_CONDUCT.md" target="_blank">code of conduct</a>.

**Comment by michael-milette** [comment]
Hi @hribeir0 ,

Thank you for your suggestion. However, you seem to just want to move the functionality of the radio buttons to buttons one step earlier. It is not clear to me why you would need to do this as the functionality already exists.

<img width="758" alt="image" src="https://github.com/michael-milette/moodle-enrol_invitation/assets/3808579/4ff2b113-8181-4dce-a8d3-69437eea47a4">

Could you please elaborate on why you need to do this?

Best regards,

Michael Milette

**Comment by hribeir0** [comment]
Thank you for taking the time to reply Michael.
If I understood correctly, you can add only one instance therefore you can send invites only for one given role (But I'm allowed to choose it). I would like to invite students, but also teachers.

**Comment by michael-milette** [comment]
Hi @hribeir0 ,

You will need to do it twice, once for the students and another for the teacher.

Best regards,

Michael
