### ISSUE TITLE
Bug: class 'core_user

### ISSUE THREAD

**Issue by gemguardian** [michael-milette/moodle-enrol_invitation#35]
### Prerequisites

- [X] I'm reporting the issue to the correct repository.
- [X] I am running the latest version of this plugin (if not, please upgrade first).
- [X] I checked the [README.md](../blob/master/README.md) and [Wiki](../wiki) documentation but did not find my answer.
- [X] I searched to make sure that this issue had not already been reported.
- [X] I have, or I know someone who has, the ability and willingness to test the fix on a Moodle LMS-based site.
- [X] I am submitting no more than one bug report per issue ticket (please do not submit multiple bugs in one issue ticket).
- [X] I understand that support is provided by volunteer(s).

### What happened?

After updating the plugin to version 2.1.2 2023050700, we cannot send invitation anymore. We get the following notification 

![image](https://github.com/michael-milette/moodle-enrol_invitation/assets/16559999/e8870958-b393-4ebe-bc9e-fbbacd11f665)

We run a Moodle 3.9 site, PHP 7.4
We have just installed/updated to the current version in the master repository and still see the same notificatin. 

We are upgrading to 4.1 / php 8 wednesday - if this will change the issue we will let you know. 

### What do you think should have happened?

I expect this needs to be solved by a programmer, which I am not :) 

### Steps to reproduce

1. Login as 'site admin"
2. Go to Course
3. Click on participants
4. click on Invite users
5. See error 

### Screenshots

![image](https://github.com/michael-milette/moodle-enrol_invitation/assets/16559999/3e2fbf75-09ad-4ba7-94e5-6927ec8b29ca)

### Moodle version

3.9

### Installed Moodle UI Language packs.

- [ ] English only
- [ ] One or more other languages/regional dialects (specify below)
- [X] Other

### If other language(s), please specify

Dutch

### Workaround

no

### Additional information

no

### System information

Client Device type:desktop
Client Operating System: Windows
Client Web Browser: chrone
Server Operating System: linux
Server Webserver: Apache
Server PHP: 7.4

### Code of Conduct

- [X] I have read and agree to the project's <a href="../blob/master/CODE_OF_CONDUCT.md" target="_blank">code of conduct</a>.

**Comment by gemguardian** [comment]
@michael-milette I can confirm that after upgrading to 4.1 the error dissapeared. I think the error I saw in 3.9 is due to Fix-30: Removed deprecated get_extra_user_fields() for Moodle 3.11, 4.0+.

**Comment by rafaelmontes8** [comment]
Im having the same error, but for other requirements I cant update to the latest moodle like the person in the original post. I'm runing 3.9 also
