### ISSUE TITLE
Feature Request: Case insensitive comparison between emails

### ISSUE THREAD

**Issue by MSVermet** [michael-milette/moodle-enrol_invitation#38]
### Prerequisites

- [X] I am requesting the new feature to the correct repository.
- [X] I checked the latest version on GitHub and the [README.md](../blob/master/README.md) documentation to ensure that this functionality does not already exist.
- [X] I searched to make sure that this feature has not already been requested.
- [X] I have, or I know someone who has, the ability and willingness to test the new feature on a Moodle LMS-based site.
- [X] I agree to submit one feature request per issue ticket (do not submit multiple requests in one issue ticket).
- [X] I understand that development and support is provided by volunteer(s) and that all final implementation decisions are up TNG Consulting Inc.

### Feature Request - The User Story

Hi Michael,

Is it possible to make the comparison between the invitation email and user email case insensitive? Currently, if a teacher doesn't notice capitals in an email address or receives the addresses without capitals from a different system, it results in students getting the message of 'Invitation intended for a different user'. 

I forked the repo and added case insensitivity to the comparison. I still need to test it properly :)

### Planning on submitting a solution in a pull request (PR)?

Yes

### Code of Conduct

- [X] I have read and agree to the project's <a href="../blob/master/CODE_OF_CONDUCT.md" target="_blank">code of conduct</a>.

**Comment by michael-milette** [comment]
Hi @MSVermet ,

Thank you so much for making the time and putting in the effort, and for your contribution. I think you had a great idea. I merged your PR into the latest release 2.2.1 of the Invitation Enrolment plugin for Moodle LMS.

Very much appreciated.

Best regards,

Michael Milette
